### ISSUE TITLE
Missing sampleProbability causes an error to be logged

### ISSUE THREAD

**Issue by rcrowe** [cerbos/cerbos#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`sampleProbability` is required based on the docs & that that `tracing.Conf.SampleProbability` is not a pointer type.

If you forget to provide a value no validation error is raised, instead you see a error log reported such as...

```
{"log.level":"warn","@timestamp":"2022-06-17T14:57:14.803Z","log.logger":"cerbos.otel","message":"OpenTelemetry error","error":"starting span \"ExportMetrics\": unsupported sampler: 0xc8b760"}
```

### Expected Behavior

Either a default value is used, like always trace (1.0) or a validation error is raised. Given it's not a pointer type on the config struct, I'm inclined to say this should be a validation error.

### Steps To Reproduce

Provide tracing config without sampling probability

```
tracing:
  exporter: otlp
  otlp:
    collectorEndpoint: "otel-collector.otel:4317"
```

**Comment by charithe** [comment]
I think this is due to a bug/feature in the OpenCensus-Otel bridge. As far as I understand, Otel doesn't recognise the OpenCensus sampler. That log message is quite annoying but it is totally harmless.
