### ISSUE TITLE
Principal filter on List Audit Log Entries Admin API Endpoint

### ISSUE THREAD

**Issue by alexolivier** [cerbos/cerbos#1041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Filtering the audit logs for actions by a particular principal ID would be useful for generating an activity feed of a user.

### What would the ideal solution look like to you?

To be able to call the List Audit Log Entries endpoint on the Admin API with a principal ID to filter the result by.

**Comment by charithe** [comment]
This requires a full scan of the audit table within a range. It's a little resource-intensive but it can be done. However, I am just wondering whether it's worth spending the time and effort building and maintaining an advanced query API into Cerbos. In a production scenario, how likely is it that operators would query each PDP individually for things like this?   

The audit system was designed with the expectation that audit entries will be aggregated into an external system (such as a SIEM) that has much more sophisticated indexing and querying capabilities. The reason we provide basic querying functionality through the Cerbos API is to give users a taste of the audit system without requiring them to install additional software. So, I am inclined to keep it that way and point users to the purpose-built solutions for any advanced use cases they may have.
