### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by lcnlvrz-revelacion** [cerbos/cerbos#1124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I just wondering if is there any plan to support mongodb as storage?

### What would the ideal solution look like to you?

Just an adapter for mongodb in order save policies would be really awesome

### Anything else?

If you think this is possible, i can start with this implementation and contribute to this project

Regards

**Comment by lcnlvrz-revelacion** [comment]
There are some concepts that doesn't exists in mongodb. For example migrations and triggers (partial). 

There is a partial equivalence of triggers in [mongodb](https://www.mongodb.com/docs/atlas/app-services/triggers/database-triggers/) but this only works if you have your mongo cluster hosted in atlas cloud, otherwise this feature does not exist. Instead of that we can use [change streams](https://www.mongodb.com/docs/manual/changeStreams/).

About migrations obviously it doesn't exists because mongodb is schemaless.

If you think i'm on the right way, let me known so then i can start implementing this feature

**Comment by danielloader** [comment]
Is this marked as completed because you can use mongodb as a storage driver, or because it was decided not to be implemented? Thanks

**Comment by charithe** [comment]
No plans to support MongoDB.
