### ISSUE TITLE
Replace github.com/rjeczalik/notify

### ISSUE THREAD

**Issue by haines** [cerbos/cerbos#1326]
On macOS 13, github.com/rjeczalik/notify has started throwing deprecation warnings during compilation.

```
# github.com/rjeczalik/notify
cgo-gcc-prolog:217:2: warning: 'FSEventStreamScheduleWithRunLoop' is deprecated: first deprecated in macOS 13.0 - Use FSEventStreamSetDispatchQueue instead. [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:1138:1: note: 'FSEventStreamScheduleWithRunLoop' has been explicitly marked deprecated here
```

It doesn't appear to be actively maintained, so we probably need to find an alternative.

**Comment by dbuduev** [comment]
I'm not getting the warning or am failing to reproduce it on macOS 13 with Apple M1 Pro CPU.

**Comment by haines** [comment]
Have you updated your Command Line Tools package in the last couple of days? I think you'd need to have 14.1 to see this.

```console
$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 14.1.0.0.1.1666437224
```

**Comment by dbuduev** [comment]
I've got the same version.
```
$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 14.1.0.0.1.1666437224
volume: /
location: /
install-time: 1667449227
groups: com.apple.FindSystemFiles.pkg-group
```


What're the steps to reproduce? Is `make compile` or `make test` enough?

**Comment by haines** [comment]
Weird, `make compile` should do it... I get this on both my M1 MacBook Pro and my Intel iMac. I can see the `API_DEPRECATED` macro in the header file, I assume it should be present for you too since you have the same CLT version?

```console
$ tail -n +1138 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h | head -n 4
FSEventStreamScheduleWithRunLoop(
  FSEventStreamRef   streamRef,
  CFRunLoopRef       runLoop,
  CFStringRef        runLoopMode) API_DEPRECATED("Use FSEventStreamSetDispatchQueue instead.", macos(10.5, 13.0), ios(6.0,16.0));
```

**Comment by dbuduev** [comment]
> I can see the API_DEPRECATED macro in the header file

I can see that too. I'll try to find out if `FSEventStreamScheduleWithRunLoop` is being called on my machine or not.

**Comment by dbuduev** [comment]
The library calls this function in a file with the following build tags: `// +build darwin,!kqueue,cgo`.

We build both `cerbos` and `cerbosctl` without CGO support, so `FSEventStreamScheduleWithRunLoop` deprecation bears no consequences. 

Some `make` targets don't configure CGO, so it remains enabled by default, hence the warning. I'll fix that.
