### ISSUE TITLE
Documentation formatting error

### ISSUE THREAD

**Issue by MattTaylorQuodd** [cerbos/cerbos#1328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/98832498/199853058-f023afd0-7f66-4a1a-b89c-6a486f13d4e2.png)
https://github.com/cerbos/cerbos/blob/v0.21/docs/modules/ROOT/pages/tutorial/02_resource-definition.adoc

this table is messed up. It should be two columns, a header row, and two data rows.

### Expected Behavior

It should probably look like this:

| Resources | Actions                        |
|-----------|--------------------------------|
| Company   | `Create, Read, Update, Delete` |
| User      | `Create, Read, Update, Delete` |

### Steps To Reproduce

1. look at this page: https://docs.cerbos.dev/cerbos/latest/tutorial/02_resource-definition.html
2. Be confused by the table
3. Realize it's a mistake
4. Open github issue to let the people know.

### Environment

```markdown
Not relevant.
```

### Anything else?

Enjoying the documentation so far.

**Comment by charithe** [comment]
Indeed! Thank you for pointing it out.
