### ISSUE TITLE
Change `DeleteSchema` RPC to be consistent with `DisablePolicy`

### ISSUE THREAD

**Issue by haines** [cerbos/cerbos#1442]
At the moment there's some inconsistency between the `DisablePolicy` and `DeleteSchema` RPCs.

- If 0 rows are deleted, `DeleteSchema` errors but `DisablePolicy` does not.
- `DeleteSchema` doesn't return the number of schemas deleted, but `DisablePolicy` returns the number of policies disabled.

I feel like these RPCs should be symmetrical, and I think the behaviour of `DisablePolicy` is preferable. I don't think 0 deletions should be a special case because you can supply multiple IDs; if it should return an error when the input IDs aren't found, then I would argue that the error condition should be rows deleted < IDs supplied, not rows deleted == 0.

I think we should remove the error condition from `DeleteSchema` and add the number of schemas deleted to the response.

**Comment by haines** [comment]
Since 0 is the default for the numeric field, to distinguish between "0 schemas were deleted" and "the response is from a version of Cerbos prior to this change" I think we need to either include a flag in the response as well, or potentially we could add the server version as a header to all responses?

**Comment by charithe** [comment]
I think that `DeleteSchema` RPC usage is quite low so we probably don't need to worry too much about the slight confusion that might arise if a newer SDK client is used to access an older server. I don't think it's worth the hassle of adding and maintaining a version check. WDYT @haines ?

Adding the server version as a header to responses is a good idea in general though. Let's do that as a new feature, either in this release or the next one.

**Comment by haines** [comment]
> I think that `DeleteSchema` RPC usage is quite low so we probably don't need to worry too much about the slight confusion that might arise if a newer SDK client is used to access an older server. I don't think it's worth the hassle of adding and maintaining a version check. WDYT @haines ?

Yep, fair enough.
