### ISSUE TITLE
Support for JWT with no "kid" in the Header

### ISSUE THREAD

**Issue by owen-c** [cerbos/cerbos#1492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I am working with an old service that currently does not sign JWTs with a "kid" in the header. Cerbos probably correctly rejects this b/c it can't find the key in the keySet to validate the signature.

I'm wondering if you'd be open to allowing Cerbos to handle this special case by just using the single key in the single keySet it was configure with instead of relying on the kid header.

Hacky for sure, but would make my life easier in the interim :)

### What would the ideal solution look like to you?

If JWT has no kid, and I only have one keyset with only one key, use that. Otherwise keep throwing the same error.

**Comment by charithe** [comment]
Is it possible for your application (or a proxy) to extract the claims from the JWT sent by this legacy application and re-encode it in the correct format? 

I can see your dilemma and would love to help here but there are few issues to consider here that would make it tricky to implement in Cerbos.

- We delegate JWT validation to a third-party library and, from a quick glance, I don't think it supports this mode. We'll have to create a special case for this scenario and then maintain that for a long time (Hyrum's law applies) -- which is not quite sustainable.
- Not quite sure whether this would weaken security or create an attack vector that we are not aware of. As a public project used by many other users, that's a big risk to take.

**Comment by owen-c** [comment]
Totally understand your reasoning, makes sense. Thanks for your response :)
