### ISSUE TITLE
Disk storage not respecting root folder

### ISSUE THREAD

**Issue by latotty** [cerbos/cerbos#1536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Loads `_schema/*.json` files as policies from deeper folders, which fails.

### Expected Behavior

Should respect the `_schema` folder in index building, and load schema files correctly.

### Steps To Reproduce

1, config disk storage to use `/cerbos` as root dir
2, Add files like `/cerbos` (`/cerbos/policy.yml`, `/cerbos/_schemas/schema.json`)
3, Run cerbos

### Environment

```markdown
- OS: Irrelevant
- Cerbos version: 0.24.0 -> 0.26.0 -> dev
- Docker version: Irrelevant
- Go version: Irrelevant
```

### Anything else?

Missing part in: https://github.com/cerbos/cerbos/blob/7570df332096dcaea0891a21f26e5c968cbecf47/internal/storage/disk/disk.go#L58
```go
idx, err := index.Build(ctx, fsys, index.WithRootDir(dir))
```

**Comment by latotty** [comment]
Sorry, the error was on our side, our folder structure was invalid (`/cerbos/policies/policies/_schemas/schema.json` with a root `/cerbos/policies`).

We changed it to be correct (the reason was a typo in the `cp` command 😅 ), now it works. 

Maybe my go knowledge is now a bit Rusty (pun intended 😄 ) but I don't know without the rootdir how it works 🤔 

Btw a more meaningful error on the cerbos side would be helpful (the current dev version's jsonschema validation helped a lot, but it's not that explicit), or support for deeper _schemas folders, where bigger projects might want to organise schemas based on units.

So anyway you could close this issue :)

**Comment by Sambigeara** [comment]
Thanks for letting us know!
