### ISSUE TITLE
Tests within `internal/server` fail on creation of Unix domain sockets with address `t.TempDir()`

### ISSUE THREAD

**Issue by Sambigeara** [cerbos/cerbos#1540]
On my system (`macOS Monterey 12.4`), running tests (`make test`) causes the following:

```
panic: failed to create listener at 'unix:/var/folders/yt/50sw1ks16gg2xgr_hzyr5d6c0000gn/T/TestServerstore=diskapiwith_tlsuds3243008092/001/grpc.sock': listen unix /var/folders/yt/50sw1ks16gg2xgr_hzyr5d6c0000gn/T/TestServerstore=diskapiwith_tlsuds3243008092/001/grpc.sock: bind: invalid argument
```

This is likely related to the length of the address string (the above is potentially above the max allowed limit). Manually crafting a temp dir using a shorter path fixes the failing tests.

**Comment by Sambigeara** [comment]
I've probably stumbled across this by chance. From a bit of reading, it seems that the path name length is limited to ~100-108 ish (platform dependent). I can assert that our temp generated names are below some arbitrarily safe number to protect against any chance occurrences in the future.

**Comment by oguzhand95** [comment]
I have updated my MacOS to `Ventura 13.3.1` and this problem started to occur for me too.
