### ISSUE TITLE
User provided CEL functions

### ISSUE THREAD

**Issue by veeral-patel** [cerbos/cerbos#1555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Cerbos includes a lot of extensions to CEL:

https://docs.cerbos.dev/cerbos/latest/policies/conditions.html

I would like to add my own CEL function, as Cerbos has done. Is there a easy way to do this without forking the code?

**Comment by charithe** [comment]
It's not possible to add your own functions without a custom build. What are the functions you want to add? If they are generally useful for most of our users, we can consider adding them to the distribution.

**Comment by veeral-patel** [comment]
It requires calls to an internal service

Feel free to close
