### ISSUE TITLE
Is Cerbos Playground open source?

### ISSUE THREAD

**Issue by veeral-patel** [cerbos/cerbos#1558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hi, sorry for all the questions (both here and in Slack)

Just wondering - is the Cerbos Playground open source? I would like to run a self hosted version of it on premise instead of developing in VS Code.

**Comment by charithe** [comment]
The playground UI is not open source. We are still doing a lot of development on it and it requires third-party infrastructure that is hard to package for an open source, self-hosted version. 

This is a common request from the community and we are thinking of ways to help address it.

**Comment by veeral-patel** [comment]
Hi @charithe - no worries. It would be great if you could open source it down the line because it provides a significantly better development environment than VS Code.

**Comment by brunorpinho** [comment]
Hi, I still [see **playgroundEnabled** flag on the configuration documentation](https://docs.cerbos.dev/cerbos/latest/configuration/server#_enable_playground) and I thought it was still supported. To avoid confusion in the future I suggest the removal of any reference from documentation.
