### ISSUE TITLE
Option to disable grpc server

### ISSUE THREAD

**Issue by michaelgmcd** [cerbos/cerbos#1595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

When running cerbos in a lambda, I get errors spinning up the gRPC server. I want startup times to be as fast as possible, and I only use HTTP.  Is it possible to disable starting of the gRPC server? I don't see any config options, and both servers fail to start if I use a port like 0000.

### What would the ideal solution look like to you?

A config option for enabling/disabling gRPC.

**Comment by charithe** [comment]
Hi. Cerbos is a gRPC server. The HTTP service is just a wrapper around gRPC. So, it can't be disabled. You can set the listening address to `127.0.0.1:0` to make it listen just on the local loopback address at a random available port though.

What is the error you see when you start Cerbos? We have users running Cerbos in lambda and hadn't had an issue before.
