### ISSUE TITLE
Question: Policy rule schema validation

### ISSUE THREAD

**Issue by scraymondjr** [cerbos/cerbos#1621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Is it expected that policy rules which reference resource attributes will validate the rule based on the resource schema, if a resource schema is defined? I've tried a quick test of this and it does not seem to be the case, but I am also not seeing explicit documentation that this behavior exists.

### What would the ideal solution look like to you?

Ideally, if a resource schema is defined, then policy rules are validated to ensure that references to resource attributes match the attributes in the defined schema. At a minimum, it would be helpful if could detect if a rule references an attribute that is not defined in the schema.

**Comment by charithe** [comment]
Not at the moment. Schemas are used to validate the incoming requests but they are not used for checking the policy definitions themselves. It's something we are planning to do in a future release.

**Comment by scraymondjr** [comment]
Thank you, and good to know. My question has been answered, so I'll leave it to you if you'd like to close this or leave it open to track the feature!
