### ISSUE TITLE
Add SDK support for `ListPolicies` filtering

### ISSUE THREAD

**Issue by Sambigeara** [cerbos/cerbos#1648]
Once cerbos/cerbos#1642 is merged, the SDKs should be updated to support the additional regex filters.

- [ ] .NET
- [ ] Go
- [ ] Java
- [ ] JavaScript: https://github.com/cerbos/cerbos-sdk-javascript/issues/562
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust

**Comment by charithe** [comment]
Most of the SDKs don't have Admin API implemented at all, unfortunately.
