### ISSUE TITLE
New Go SDK module free from indirect dependencies

### ISSUE THREAD

**Issue by rcrowe** [cerbos/cerbos#1650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

When pulling in `github.com/cerbos/cerbos/client` it's currently pulling 81 indirect dependencies, a lot of which is not required for the client to operate over the gRPC API.

It would be great if there was a Go module specific to the client.

### What would the ideal solution look like to you?

**go.mod:**

```shell
module github.com/cerbos/cerbos/client
```

**Comment by charithe** [comment]
This is something we've wanted to do for a while. The tricky part is extricating the calls to the internal packages in the main Cerbos module. Do you use the testing features provided by the SDK such as starting up an in-process Cerbos instance? I am thinking that the path of least resistance would be to split the API client into its own module without the testing and other utility features that it currently includes.

**Comment by rcrowe** [comment]
To be honest, we do not actually use the current Client SDK because of this & a few other challenges for us, instead, we wrap the gRPC API ourselves.

Having test/debug functionality as a separate module that requires deeper integration with Cerbos seems fair.

**Comment by charithe** [comment]
https://github.com/cerbos/cerbos-sdk-go
