### ISSUE TITLE
Helm Chart reconfiguration is not recreating a Pod

### ISSUE THREAD

**Issue by danka-orgnostic** [cerbos/cerbos#1692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After changing/ adding variables in helm chart, old pod is still running. In order to update chart, we need to manually restart cerbos deployment or to delete and create deployment again.

### Expected Behavior

New Pod should be created and old one terminated after changing parameters in helm chart.

### Environment

```markdown
- OS: Amazon Linux 2
- Cerbos version: 0.28.0
- Container Runtime Version: containerd://1.6.19
- Kubelet Version: v1.24.13-eks-0a21954
```

**Comment by haines** [comment]
I'm assuming you mean the variables that are ultimately interpolated into the Cerbos config file? It would make sense for us to add the checksum of the configmap to the pod annotations in the deployment so that it'll get rolled when the config changes.

**Comment by danka-orgnostic** [comment]
Yes, thanks. :)
