### ISSUE TITLE
Principal ID regex is too restrictive

### ISSUE THREAD

**Issue by dbuduev** [cerbos/cerbos#1695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The principal policy protobuf definition has a regex for a principal (principal ID):

 ```protobuf
message PrincipalPolicy {
  string principal = 1 [(validate.rules).string = {
    pattern: "^[[:alpha:]][[:word:]\\@\\.\\-]*(\\:[[:alpha:]][[:word:]\\@\\.\\-]*)*$",
    min_len: 1
  }];
  string version = 2 [(validate.rules).string.pattern = "^[[:word:]]+$"];
  repeated PrincipalRule rules = 3;
  string scope = 4 [(validate.rules).string.pattern = "^([[:alnum:]][[:word:]\\-]*(\\.[[:word:]\\-]*)*)*$"];
  Variables variables = 5;
}
```

This regex forbids the Amazon Resource Names (ARNs) pattern, which may include consecutive colons `::` and a slash `/`. 
For example, `arn:aws:iam::acct123-44:user/567-99803848`.

### What would the ideal solution look like to you?

Less restrictive regex.

**Comment by juselius** [comment]
This is causing trouble for us too. I'll make a PR in a moment.

**Comment by charithe** [comment]
I think this is slightly more complicated than just changing the regex because the principal name is part of the policy identity. We need to carefully review the places where we use plaintext policy identifiers to make sure nothing breaks.

**Comment by juselius** [comment]
Ok, I see. The following  PCRE fixes the matching for ARNs:

```
"^[[:alpha:]][[:word:]@.-]*([:/]+[[:word:]@.-]*)*$"
```

**Comment by jesumyip** [comment]
I use Auth0 and Okta. Auth0 is configured to use Okta as a Oauth2 Idp. As a result, all the user-ids are JIT created in Auth0 from the Okta user and end up having a user-id of `oauth2|auth0-connection-name|okta-userid`. The `|` pipe character is being rejected by the regex as well.

**Comment by juselius** [comment]
This also affects `roles `and `derivedRoles`, which currently cannot contain characters like`:+/`, which is quite annoying when interacting with for example kubernetes roles like `system:basic-user`.
