### ISSUE TITLE
Are policies updated in-memory after being added or updated to the database?

### ISSUE THREAD

**Issue by veeral-patel** [cerbos/cerbos#1741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I'm using Postgres for storing policies.

However, I'd like to know - if I insert a policy into the database, or update a policy in the DB, do running Cerbos instances somehow get updated with the new policies?

Details --

My understanding is Cerbos instances read policies from the database or disk into a in-memory data structure at startup, and evaluate check permission requests using these in-memory policies.

However, do Cerbos instances also periodically poll the database and update their in-memory data structure?

**Comment by charithe** [comment]
We've added a [section to the docs](https://docs.cerbos.dev/cerbos/latest/configuration/storage#postgres-db-sync) explaining the caveats.

**Comment by veeral-patel** [comment]
That was fast, thank you!
