### ISSUE TITLE
Hibernate/JPA Query Plan Adapter

### ISSUE THREAD

**Issue by veeral-patel** [cerbos/cerbos#1742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I'd like a Hibernate/JPA Query Plan adapter for filtering resources.

### What would the ideal solution look like to you?

Just as we have adapters for Prisma and SQLAlchemy, I wanted one for Hibernate/JPA. Or, I can write it myself if it's not something that will be done soon.

**Comment by charithe** [comment]
This is something we'd like to do but it's not on our immediate road map. If you develop one with a permissive licence please let us know and we could promote it to the wider community.

**Comment by veeral-patel** [comment]
Sure, I can let you know if I do this. Feel free to close this issue if there's nothing actionable here.
