### ISSUE TITLE
Update recommended nvim package manager in docs

### ISSUE THREAD

**Issue by Sambigeara** [cerbos/cerbos#1803]
[Packer](https://github.com/wbthomason/packer.nvim) is currently (as of August) unmaintained. I'm not sure if this will change, but if support drops, we should update [the documentation example](https://docs.cerbos.dev/cerbos/latest/policies/authoring_tips#_neovim) with the next best package manager.

**Comment by charithe** [comment]
Oh no! There goes the rest of my day 🥲

**Comment by Sambigeara** [comment]
I'm sorry
