### ISSUE TITLE
Make the matched action available to conditions

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#1825]
If there's rule with a wildcard action (`actions: ['*']`) then it's sometimes useful to know which action triggered the rule. For example, a user could have a wildcard DENY rule to deny all actions except a particular action. Because DENY takes precedence, there's currently no way to express this in a policy.

**Comment by charithe** [comment]
Duplicate of #1828

**Comment by haines** [comment]
Oops, thanks 🙈
