### ISSUE TITLE
CORS Error on Firefox

### ISSUE THREAD

**Issue by msp-ampcome** [cerbos/cerbos#1842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, We are using Cerbos to authorize features on our frontend application, we are using the isAllowed method from the Cerbos JS SDK to implement this feature. This is working fine on all the browsers except for Firefox. If we try the application on Chrome or Edge, Cerbos API is properly responding. 

When we use firefox, **/api/check/resources** is throwing CORS error.

We have configured the CORS properly on Cerbos config as per the documentation.

### Expected Behavior

/api/check/resources should respond properly on Firefox.

### Environment

```markdown
- OS:
- Cerbos version: 0.26.0
- Docker version: 
- Go version:
```

**Comment by alexolivier** [comment]
@msp-ampcome do you have an example of the error? Is there a header or such being flagged?
