### ISSUE TITLE
Issue with multiple replicas and git backend

### ISSUE THREAD

**Issue by maxrad82** [cerbos/cerbos#1846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running 4 replicas (might be the same with 3) of cerbos in a kubernetes cluster with a git backend, from time to time some pods doesn't return the same results (only when requesting for scoped resources). Sometimes it's fine and the audit logs show that the used policy is the scoped one and sometimes it's not fine and the audit logs show that the used policy is the default one (it is like it didn't find the scoped resource policy file). It seems to happen after a while when a pod has started. We are using cerbos 0.30. We were prior using cerbos 0.27 and i don't recall having this issues. We are using lenientScope: true

these are the 2 audit entries:

---- result ok  ----

"checkResources": {
      "inputs": [
        {
          "resource": {
            "kind": "vod:object",
            "id": "3b70b7f5-b419-4899-83b5-d15dbe67fa42",
            "attr": {
              "media": "null",
              "event": "{\"category\":\"Interview\", \"id\":\"3b70b7f5-b419-4899-83b5-d15dbe67fa42\", \"organizers\":[], \"path\":\"/85f6a9e8-eaef-460b-875b-e39f81a99c0e/3b70b7f5-b419-4899-83b5-d15dbe67fa42\", \"startDate\":\"2022-10-06\"}"
            },
            "scope": "jfr2022"
          },
          "actions": [
            "media:view"
          ],
          "requestId": "0409312c-a80a-4231-a7cf-6208d4a77074",
          "principal": {
            "roles": [
              "user",
              "sfr-member"
            ],
            "attr": {
              "organizations": "[]",
              "accessDays": "[]",
              "badgesTypes": "[]",
              "badgesOptions": "[]"
            },
            "id": "74018003-c6a6-4304-9c35-4d6cb96ac8e2"
          }
        }
      ],
      "outputs": [
        {
          "resourceId": "3b70b7f5-b419-4899-83b5-d15dbe67fa42",
          "requestId": "0409312c-a80a-4231-a7cf-6208d4a77074",
          "actions": {
            "media:view": {
              "effect": "EFFECT_ALLOW",
              "scope": "jfr2022",
              "policy": "resource.vod_object.vdefault/jfr2022"
            }
          }
        }
      ]
    }

---- result ko  ----

"checkResources": {
      "inputs": [
        {
          "requestId": "533d1a17-a78a-4830-9b8f-015d7c32da04",
          "principal": {
            "attr": {
              "organizations": "[]",
              "accessDays": "[]",
              "badgesTypes": "[]",
              "badgesOptions": "[]"
            },
            "id": "74018003-c6a6-4304-9c35-4d6cb96ac8e2",
            "roles": [
              "user",
              "sfr-member"
            ]
          },
          "resource": {
            "kind": "vod:object",
            "id": "3b70b7f5-b419-4899-83b5-d15dbe67fa42",
            "attr": {
              "media": "null",
              "event": "{\"category\":\"Interview\", \"id\":\"3b70b7f5-b419-4899-83b5-d15dbe67fa42\", \"organizers\":[], \"path\":\"/85f6a9e8-eaef-460b-875b-e39f81a99c0e/3b70b7f5-b419-4899-83b5-d15dbe67fa42\", \"startDate\":\"2022-10-06\"}"
            },
            "scope": "jfr2022"
          },
          "actions": [
            "media:view"
          ]
        }
      ],
      "outputs": [
        {
          "resourceId": "3b70b7f5-b419-4899-83b5-d15dbe67fa42",
          "requestId": "533d1a17-a78a-4830-9b8f-015d7c32da04",
          "actions": {
            "media:view": {
              "effect": "EFFECT_DENY",
              "policy": "resource.vod_object.vdefault"
            }
          }
        }
      ]
    },

### Expected Behavior

all cerbos instance should behave the same and give the same results

### Environment

```markdown
- OS:
- Cerbos version: 0.30 (official docker image)
- Docker version:
- Go version:
```

**Comment by maxrad82** [comment]
Hello, well i just captured the audit log for a specific request showing that the specified scope was not the right one.Our git poll interval is 1 minute. I noticed that when it happened, it happened only on a specific instance of cerbos. Making requests on that instance always returned the wrong result (so it's not a random result). I tried to reproduced it locally (using a very short git polling interval) but without success. When the instance was not working as expected only a restart seemed to fix it.

**Comment by charithe** [comment]
You don't happen to have the logs from that Cerbos instance, do you? Sounds like it stopped polling git but there's no obvious way for that to happen as far as I can see. An error message would be really helpful to track the cause down.

**Comment by maxrad82** [comment]
Sorry for the late reply, but we didn't encounter the issue for quite some time. It happened recently and I have the error log when it's happenning:

14T13:13:56.070Z","log.logger":"cerbos.git.store","message":"Failed to check for updates","dir":"/work","error":"failed to pull from remote: Get \"https://git.srvteam.com/congress/microservices/policies.git/info/refs?service=git-upload-pack\": read tcp 172.25.51.226:36480->192.168.224.21:443: read: connection reset by peer"}

Obviously the gitlab server returned an error but it should not impact the existing rules

**Comment by charithe** [comment]
Thanks for providing the details. We're trying to replicate this on our end (with no luck so far). We'll get back to you with the findings.

**Comment by oguzhand95** [comment]
Hi @maxrad82,

We have tried to test what happens if Cerbos loses connectivity to the Git server. In our test, we used the toxiproxy tool to generate a `reset_peer` error on the Cerbos side.

The steps and their results for the test:
- Started Cerbos pointing to an empty (no policies) Git repository
- Cerbos cloned the repository
- After the `updatePollInterval`, Cerbos successfully checked the updates on the remote repository and found no updates as we expected
- Sent a `CheckResources` request to Cerbos for non-existent resources and got the `EFFECT_DENY` response as expected
- Added a `reset_peer` toxic to the connection between Cerbos and Git using toxiproxy
- After the `updatePollInterval`, Cerbos failed to update the clone of the Git repository as expected
- Added a `leave_request.yaml` resource policy to the Git repository
- After the `updatePollInterval`, Cerbos failed to update the clone of the Git repository as expected
- Sent a `CheckResources` request to Cerbos and got an `EFFECT_DENY` response as expected (since the clone is not updated yet)
- Deleted the `reset_peer` toxic from the connection between Cerbos and Git
- After the `updatePollInterval`, Cerbos successfully updated the clone of the Git repository
- Sent a `CheckResources` request to Cerbos (resource: leave_request) and Cerbos responded with `EFFECT_ALLOW`

So, in our tests, Cerbos was able to recover from connectivity issues to the Git server and refresh itself. We are not sure what's happening in your environment. Could it be due to a network partition happening in the container network? The other possibility we can think of is the Git server throttling the connection but that'd usually show up in the logs.

**Comment by oguzhand95** [comment]
Thanks for providing more details, we've conducted more tests but still couldn't reproduce the problem in our environment.

Would it be possible for you to send a `SIGUSR1` to Cerbos, and send a request as you've described above next time this happens? If you share the logs with us after these steps, we could inspect them to search for the problem.

**Comment by maxrad82** [comment]
Hi,

After some investigations, we succeed to reproduce the issue that is, in fact not related to git storage (we disabled it, and we can reproduce it locally with a filesystem storage).

Here is the step to reproduce:

we have 2 policies:
- a default one that gives access to principal with a specific role
- a scoped one that gives access to any roles
- we make a request asking for the a scoped resource with a role that is not declared in the default policy => result is ok
- we spam the server with requests (consecutive requests) for a few seconds
- we restart the cerbos server (that is run in a container)
- we make a request asking for a resource with a non existing scope, default policy is used => ok
- we make the request that ask for the same scoped resource than in first place => default policy is used => ko

I put an archive in attachment:

- you can run make to start the cerbos server with the test policies used within a container
- make the request to validate that the result is correct
- then in an other terminal you can run the test.sh that will spam cerbos with requests, you can let it run for 10 seconds and abort it
[test.tar.gz](https://github.com/cerbos/cerbos/files/14788342/test.tar.gz)

- restart the cerbos container
- make the same requests but with a scope that doesn't exist so that it uses the default policy
- make the same request with the existing scope and voila the result is not the one expected

**Comment by charithe** [comment]
Thanks for the detailed reproduction instructions. Cerbos doesn't hold any state so restarting the container after overloading it shouldn't have any impact on how it behaves the second time around. I think the root cause is a cache invalidation bug. We'll rollout a fix ASAP.
