### ISSUE TITLE
Installing Helm chart from OCI registry fails with 401 error

### ISSUE THREAD

**Issue by fabsrc** [cerbos/cerbos#1858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Installing the Cerbos Helm chart using the [OCI registry](https://docs.cerbos.dev/cerbos/latest/installation/helm) (`oci://ghcr.io/cerbos/helm-charts/cerbos`) fails with an `401 Unauthorized` error.

### Expected Behavior

Cerbos Helm chart is installable from the OCI registry (`oci://ghcr.io/cerbos/helm-charts/cerbos`) 

### Steps To Reproduce

Run `helm install` command as described in the [docs](https://docs.cerbos.dev/cerbos/latest/installation/helm)

```sh
HELM_EXPERIMENTAL_OCI=1 helm install cerbos oci://ghcr.io/cerbos/helm-charts/cerbos --version=0.31.0
```

Returns error:

```
Error: INSTALLATION FAILED: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Acerbos%2Fhelm-charts%2Fcerbos%3Apull&service=ghcr.io: 401 Unauthorized
```

After logging in to GHCR, it returns this error:

```
Error: INSTALLATION FAILED: unexpected status from HEAD request to https://ghcr.io/v2/cerbos/helm-charts/cerbos/manifests/0.31.0: 403 Forbidden
```

### Environment

```markdown
- OS: MacOS 14.0
- Cerbos version: 0.31.0
- Helm version: 3.13.1
- Docker version: 24.0.6
- Go version: -
```

### Anything else?

It seems like the `helm-charts` repo is currently not set to "public" in the packages: https://github.com/orgs/cerbos/packages?visibility=public

**Comment by charithe** [comment]
Thanks for reporting. It should be working now. Please re-open the issue if not.
