### ISSUE TITLE
Typo in docs causes sample test to fail.

### ISSUE THREAD

**Issue by johnfkraus** [cerbos/cerbos#1927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On this page:

https://docs.cerbos.dev/cerbos/latest/tutorial/02_resource-definition

The policy for the contact resource seems to allow a user to delete a contact, as follows:

---
apiVersion: api.cerbos.dev/v1
resourcePolicy:
version: "default"
resource: "contact"
rules:
- actions:
- create
- read
- update
- delete   # <=== ==================  !!
effect: EFFECT_ALLOW
roles:
- user

    - actions:
        - "*"
      effect: EFFECT_ALLOW
      roles:
        - admin

Allowing the user to delete a contact causes a failure in the test described on this subsequent page:

https://docs.cerbos.dev/cerbos/latest/tutorial/04_testing-policies

The following excerpt from the yaml test file from the above web page shows user is not expected to be able to delete:

- principal: user
  resource: contact
  actions:
  create: EFFECT_ALLOW
  read: EFFECT_ALLOW
  update: EFFECT_ALLOW
  delete: EFFECT_DENY  # <===

Therefore, I get the following result, following the letter of your documentation.

```bash
 cerbos compile --tests=tests policies
Test results
└─┬ContactTestSuite (contact_test.yaml) [7 OK] [1 FAILED]
  └─┬Contact CRUD Actions
    └─┬user
      └─┬contact
        └─┬delete [FAILED]
          └──OUTCOME: expected: EFFECT_DENY, actual: EFFECT_ALLOW

8 tests executed [7 OK] [1 FAILED]
```
The documentation does not seem to anticipate this test failure (although I found it instructive).

To fix this seeming error, I would proposed to delete line 11 of this file:
https://github.com/cerbos/cerbos/blob/main/docs/modules/ROOT/examples/tutorial/03-resource-definition/cerbos/policies/contact.yaml

The line I propose to excise would remove "- delete" from the allowed user actions.  

Please advise.

### Expected Behavior

cerbos compile --tests=tests policies
Test results
└──ContactTestSuite (contact_test.yaml) [8 OK]

### Steps To Reproduce

Follow the tutorial exactly starting from here: https://docs.cerbos.dev/cerbos/latest/tutorial/02_resource-definition
through https://docs.cerbos.dev/cerbos/latest/tutorial/04_testing-policies.  

### Environment

```markdown
- OS: MacOS
- Cerbos version: 0.32.0
- Docker version: N/A
- Go version: go version go1.16.5 darwin/amd64
```

**Comment by charithe** [comment]
Thanks for reporting 🙏🏽
