### ISSUE TITLE
demo-python failes to start

### ISSUE THREAD

**Issue by msigal** [cerbos/cerbos#1947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[demo-python](https://github.com/cerbos/demo-python) contains the following bug

[derived_roles_1.yml](https://github.com/cerbos/demo-python/blob/master/policies/derived_roles_1.yml)

```
...
derived_roles:
...
```
gives log

> "Index build failed","missing":[{
>     "importing_file":"resource_policy_1.yml",
>     "desc":"Derived roles import 'my_derived_roles' not found"
> }],
> "load_failures":[{
>     "file":"derived_roles_1.yml",
>     "error":"file is not valid: { "
>             "/: [additionalProperties 'derived_roles' not allowed | "
>             "missing properties: 'derivedRoles' | "
>             "missing properties: 'exportVariables' | "
>             "missing properties: 'principalPolicy' | "
>             "missing properties: 'resourcePolicy'] "
>             "}"}
> ]}

### Expected Behavior

> derived_roles ---> derivedRoles 

fixes the problem.

### Steps To Reproduce

```
git clone https://github.com/cerbos/demo-python.git 
cd demo-python
./pw demo
```

### Environment

```markdown
- OS: mac
- Cerbos version:
- Docker version:
- Go version:
```

**Comment by charithe** [comment]
Thanks for reporting.
