### ISSUE TITLE
Git file transport does not work inside the container image

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#20]
We can't point to a git repository using the `file` protocol when the application is run as a container.

```
failed to clone from file:///work/git-repo to /work/work-dir: exec: \"git\": executable file not found in $PATH"
```

Obviously, the Distroless base image does not have git installed and neither do we want to ship git with the application. It's odd that `go-git` uses the binary in the first place. Maybe we are using it wrong.

https://github.com/go-git/go-git/blob/b5b59f5fc9f9c0cd3ad1329c814b6a0d8126e675/plumbing/transport/file/client.go

**Comment by dbuduev** [comment]
It was easy to write a failing test by resetting `PATH` with https://pkg.go.dev/testing#T.Setenv.
I tried to fix the test and discovered the use case is not supported by `go-git`.

From https://github.com/go-git/go-git/blob/master/COMPATIBILITY.md

> 
Feature | Status | Notes
-- | -- | --
file:// | partial | Warning: this is not pure Golang. This shells out to the git binary.

I suggest closing the issue.

**Comment by charithe** [comment]
Thanks for looking into it. We can just add a note to the documentation to say that the file transport is not supported by the container.
