### ISSUE TITLE
Update demo-rest to use the new Cerbos Go SDK

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#2050]
The [demo-rest](https://github.com/cerbos/demo-rest) repository is still using the old Cerbos SDK and should be moved to use the new SDK.

**Comment by charithe** [comment]
Sure, go for it.

**Comment by SuperAayush** [comment]
PR - https://github.com/cerbos/demo-rest/pull/34

**Comment by SuperAayush** [comment]
@charithe I think we can close this issue as well.

**Comment by charithe** [comment]
Thanks!
