### ISSUE TITLE
Not able to login inside container  using bin/bash command

### ISSUE THREAD

**Issue by AvinashDalvi89** [cerbos/cerbos#2051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running `docker exec CONTAINER_ID -it /bin/bash` getting below error. 

OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

I think in Dockerfile or image need to enable this command. 

### Expected Behavior

Anyone should able to logged into container by running this command `docker exec CONTAINER_ID -it /bin/bash` 

### Steps To Reproduce

1. docker ps -a 
2. Find out container id and copy 
3. run this `docker exec CONTAINER_ID -it /bin/bash` 

### Environment

```markdown
- OS: MacOS 
- Cerbos version: 0.34.0
- Docker version: 4.20.1 (110738)
- Go version:
```

### Anything else?

I need to login in container to check policy and resources file are map rightly or not. Facing some issue.

**Comment by charithe** [comment]
The Cerbos container doesn't include an OS. This is to keep the security surface as minimal as possible. If you're unsure about your volume mounts, you can test them out with another container that has an OS. As long as the volume mount command is correct, it should work the same way across all containers.  

If you absolutely need to obtain a shell, you can use a tool like [cdebug](https://github.com/iximiuz/cdebug) with Docker or a debug container if you're on Kubernetes.
