### ISSUE TITLE
Enhance the Issue template

### ISSUE THREAD

**Issue by FatumaA** [cerbos/cerbos#2071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is no checkbox for external contributors to indicate interest in solving any issue they create in the repository.

### Expected Behavior

There should be a way or a checkbox at the time of creating a new issue that allows the contributor to clearly indicate interest in fixing the issue. 

In most cases, a new issue has to be triaged and is not immediately ready for contributors, this can be a good way for the maintainer to know to either assign them the issue or to let them know otherwise. 

### Steps To Reproduce

1. Click on the "New issue" button in the repository
2. Notice the template has no way to indicate interest in fixing the new issue being filed

### Environment

```markdown
- OS:
- Cerbos version:
- Docker version:
- Go version:
```

### Anything else?

Here is a screenshot from [Documenso](https://github.com/documenso/documenso)'s issue template that illustrates this well: 

![Screenshot 2024-03-27 at 11 25 18](https://github.com/cerbos/cerbos/assets/67555014/97c024df-98c1-4879-8235-9ccafe958dd5)

**Comment by charithe** [comment]
You could just state in the issue body that you would like to tackle it yourself 🙂

**Comment by FatumaA** [comment]
> You could just state in the issue body that you would like to tackle it yourself 🙂

Yeah that works too 😁 It's a suggestion to nudge the contributor incase they forget. Def not a priority.

**Comment by charithe** [comment]
Thanks for your suggestion and sorry we didn't realise that you wanted to fix the previous issue you raised. I'm not a huge fan of complicated issue templates and prefer to keep them as simple as possible without too much administrivia. So, let's keep it as it is and revisit if another such misunderstanding happens.

**Comment by FatumaA** [comment]
> Thanks for your suggestion and sorry we didn't realise that you wanted to fix the previous issue you raised. I'm not a huge fan of complicated issue templates and prefer to keep them as simple as possible without too much administrivia. So, let's keep it as it is and revisit if another such misunderstanding happens.

Not a problem at all 🙂
