### ISSUE TITLE
Add values schema to the cerbos helm chart

### ISSUE THREAD

**Issue by petar-cvit** [cerbos/cerbos#2223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hey, could we add the [values.schema.json](https://helm.sh/docs/topics/charts/#schema-files) to the helm chart? We are working on a [tool](https://github.com/cyclops-ui/cyclops) that renders UIs for helm charts based on their schema and would love to support the cerbos chart as well.

### What would the ideal solution look like to you?

Add the values.schema.json to the chart. Initialy, the schema can cover just the basic set of fields so its easier to maintain.

### Anything else?

I would like to take the issue and add the schema.

**Comment by charithe** [comment]
This is something that has been in the list for a long time. Thanks for the nudge.

We allow users to directly inject Kubernetes objects (e.g. `initContainers`) into the chart. It's tedious to write those schemas by hand and keep them updated with Kubernetes releases. Have you come across a way to make that easier? I wanted to add `$ref`s to https://kubernetesjsonschema.dev but that hasn't been updated for several years.

**Comment by petar-cvit** [comment]
I searched for tools to help us automate the process and use them for our charts, but was not lucky. A lot of them depend on values.yaml comments, which again require a fair share of maintenance.

However, for our case and the tool we are building, we could add a basic schema with fields that won't likely change but would allow us to support cerbos.

Let me know if you think adding a schema with just a subset of fields makes sense on your end, and if it does, we would be happy to open a PR with it.

**Comment by charithe** [comment]
The PR is already open (#2230) 🙂  

What I meant was that I am not quite happy with marking `initContainers` as an array of objects when I know that the objects are [Containers](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container) with their own well-known schema. I was hoping you had a catalogue of schemas for Kubernetes API objects that we could simply link to using a `$ref`.
