### ISSUE TITLE
Using alpine base image instead of scratch

### ISSUE THREAD

**Issue by afifurrohman-id** [cerbos/cerbos#2291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

It would be useful for something like running repl, from existing cerbos container that already running, some shell like `sh` is really useful.

also will helper when run `nomad` jobs and execute cerbos job, currently **is not possible**

### What would the ideal solution look like to you?

using alpine base image

### Anything else?

may be just opt in add an `alpine` release tag

**Comment by charithe** [comment]
Hi. We intentionally ship a minimal image to keep the security surface as small as possible and avoid spurious security alerts from scanners that detect issues with system libraries shipped with Alpine and other "fat" base images.

Cerbos has a very simple configuration so there's nothing much you can debug by obtaining a shell anyway. If you really must, you can use tools like [`kubectl debug`](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_debug/) or [cdebug](https://github.com/iximiuz/cdebug) to attach a debug container to Cerbos.

I am not very familiar with Nomad but it's quite strange that it would require a shell on the container to work. If that's absolutely the case, I suggest creating your own Cerbos image using something like the following: 

```dockerfile
FROM ghcr.io/cerbos/cerbos:latest AS base
FROM alpine
COPY --from=base /cerbos /cerbos
ENTRYPOINT ["/cerbos"]
CMD ["server"]
```
