### ISSUE TITLE
Admin API: Add policy with derived roles `proto: (line 21:7): error parsing \"resourcePolicy\", oneof cerbos.policy.v1.Policy.policy_type is already set`

### ISSUE THREAD

**Issue by afifurrohman-id** [cerbos/cerbos#2293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

WIth this payload:
```json
{
  "policies": [
    {
      "apiVersion": "api.cerbos.dev/v1",
      "resourcePolicy": {
        "resource": "foo",
        "version": "default",
        "importDerivedRoles": [
          "tenant_roles"
        ],
        "rules": [
          {
            "actions": [
              "view"
            ],
            "derivedRoles": [
              "customer"
            ],
            "effect": "EFFECT_ALLOW"
          }
        ],
        "scope": "a"
      },
      "derivedRoles": {
        "name": "tenant_roles",
        "definitions": [
          {
            "name": "customer",
            "parentRoles": [
              "user"
            ],
            "condition": {
              "match": {
                "expr": "R.tenant in P.tenants"
              }
            }
          }
        ]
      }
    }
  ]
}
```

When make request to `PUT http://localhost:3592/admin/policy`
it will  result:
`proto: (line 21:7): error parsing \"resourcePolicy\", oneof cerbos.policy.v1.Policy.policy_type is already set`

base on this proto: https://github.com/cerbos/cerbos/blob/main/api/public/cerbos/policy/v1/policy.proto#L36
does it means we only can send either derived roles / resourcePolicy / principal policy at a  time? 

### Expected Behavior

because we expect if there is a `import derived roles` there also should be a `derived roles` or if not need to documented.

### Steps To Reproduce

curl cmd:
```sh
curl -X PUT "http://localhost:3592/admin/policy" \
 -H "accept: application/json"\
 -H "authorization: Basic <your-auth-token>"\
 -H "content-type: application/json" \
 -d '{"policies":[{"apiVersion":"api.cerbos.dev/v1","resourcePolicy":{"resource":"foo","version":"default","importDerivedRoles":["tenant_roles"],"rules":[{"actions":["view"],"derivedRoles":["customer"],"effect":"EFFECT_ALLOW"}],"scope":"a"},"derivedRoles":{"name":"tenant_roles","definitions":[{"name":"customer","parentRoles":["user"],"condition":{"match":{"expr":"R.tenant in P.tenants"}}}]}}]}' 

```

### Environment

- OS: 
```
uname -a
Linux cerbos 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 GNU/Linux
```
- Cerbos version:
```json
{
  "version": "0.37.0",
  "commit": "bf41e876bb0e81688964e9c901ac898faa25ac8e",
  "buildDate": "2024-06-18T07:55:51Z"
}
```
- Docker version:
```
Client: Docker Engine - Community
 Version:    27.0.3

Server:
 Server Version: 27.0.3
```
- Go version:
```
go version go1.23.0 linux/amd64
```

### Anything else?

This should add to docs. otherwise if need more time, may give link to `proto` file for api would really helpful.

thankyou

**Comment by charithe** [comment]
Hello. You can send multiple policies to the API. The problem with your request is that you merged two policies into one. The payload needs to be like this:

```json
{
  "policies": [
    {
      "apiVersion": "api.cerbos.dev/v1",
      "resourcePolicy": {
        "resource": "foo",
        "version": "default",
        "importDerivedRoles": [
          "tenant_roles"
        ],
        "rules": [
          {
            "actions": [
              "view"
            ],
            "derivedRoles": [
              "customer"
            ],
            "effect": "EFFECT_ALLOW"
          }
        ],
        "scope": "a"
      }
    },
    {
      "apiVersion": "api.cerbos.dev/v1",
      "derivedRoles": {
        "name": "tenant_roles",
        "definitions": [
          {
            "name": "customer",
            "parentRoles": [
              "user"
            ],
            "condition": {
              "match": {
                "expr": "R.tenant in P.tenants"
              }
            }
          }
        ]
      }
    }
  ]
}

**Comment by afifurrohman-id** [comment]
> Hello. You can send multiple policies to the API. The problem with your request is that you merged two policies into one. The payload needs to be like this:
> 
> ```json
> {
>   "policies": [
>     {
>       "apiVersion": "api.cerbos.dev/v1",
>       "resourcePolicy": {
>         "resource": "foo",
>         "version": "default",
>         "importDerivedRoles": [
>           "tenant_roles"
>         ],
>         "rules": [
>           {
>             "actions": [
>               "view"
>             ],
>             "derivedRoles": [
>               "customer"
>             ],
>             "effect": "EFFECT_ALLOW"
>           }
>         ],
>         "scope": "a"
>       }
>     },
>     {
>       "apiVersion": "api.cerbos.dev/v1",
>       "derivedRoles": {
>         "name": "tenant_roles",
>         "definitions": [
>           {
>             "name": "customer",
>             "parentRoles": [
>               "user"
>             ],
>             "condition": {
>               "match": {
>                 "expr": "R.tenant in P.tenants"
>               }
>             }
>           }
>         ]
>       }
>     }
>   ]
> }
> ```

Thankyou for explanation.
