### ISSUE TITLE
Do not allow creating remote branches on upstream repo

### ISSUE THREAD

**Issue by aliok** [cerbos/cerbos#233]
Developers should create branches on their repos. No upstream branches should be there, except maybe release related branches (depends on the development and release process).

Tasks:
- [ ] Make sure developers do `git remote set-url --push origin no_push`
- [ ] [optional] Disable it on Github (not sure how, other than using something like Prow)

**Comment by isdevx** [comment]
Hey @aliok thanks for the feedback! This is purely a matter of taste. However, we tend to use a similar workflow and only maintainers can create branches on upstream. There is only my branch currently which is going to be deleted once it get merged.

**Comment by isdevx** [comment]
This is added to our development process docs, thanks again @aliok :rocket: Closing the issue as there are no development branches on upstream.
