### ISSUE TITLE
Prefer squash commits over merge commits

### ISSUE THREAD

**Issue by aliok** [cerbos/cerbos#234]
In my personal opinion, merge commits are just creating a mess. It is hard to understand the commit history.

I would disable merge commits and only squash the PRs. That makes sure the commit history is linear.
If you still want to check individual commits, you can go to Github and check them out (PR number is in the commit message)

https://docs.github.com/en/github/administering-a-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Comment by isdevx** [comment]
Thanks @aliok makes sense, we already use that :)
<img width="294" alt="image" src="https://user-images.githubusercontent.com/87911166/128596275-682125f0-3e39-4b9d-9939-a16784d187cb.png">

**Comment by aliok** [comment]
Ah, ok, I saw a feature branch on the remote repository and I was thinking this was allowed.

Thanks for the clarification.
