### ISSUE TITLE
CORS broken on Safari

### ISSUE THREAD

**Issue by klafbang** [cerbos/cerbos#2342]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Trying to access a web application using Cerbos fails with a CORS warning:

![Image](https://github.com/user-attachments/assets/1126605b-612f-4f4b-a507-4c24b4bba83d)

Trying to fetch the CORS headers manually, I get:

```
> curl -v -X OPTIONS https://cerbos.acceptance.gf.ocs.nu/api/check/resources -H "Origin: https://riga.acceptance.gf.ocs.nu"
* Host cerbos.acceptance.gf.ocs.nu:443 was resolved.
* IPv6: (none)
* IPv4: 161.35.247.137
*   Trying 161.35.247.137:443...
* Connected to cerbos.acceptance.gf.ocs.nu (161.35.247.137) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=cerbos.acceptance.gf.ocs.nu
*  start date: Oct 14 13:35:17 2024 GMT
*  expire date: Jan 12 13:35:16 2025 GMT
*  subjectAltName: host "cerbos.acceptance.gf.ocs.nu" matched cert's "cerbos.acceptance.gf.ocs.nu"
*  issuer: C=US; O=Let's Encrypt; CN=R10
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://cerbos.acceptance.gf.ocs.nu/api/check/resources
* [HTTP/2] [1] [:method: OPTIONS]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: cerbos.acceptance.gf.ocs.nu]
* [HTTP/2] [1] [:path: /api/check/resources]
* [HTTP/2] [1] [user-agent: curl/8.7.1]
* [HTTP/2] [1] [accept: */*]
* [HTTP/2] [1] [origin: https://riga.acceptance.gf.ocs.nu]
> OPTIONS /api/check/resources HTTP/2
> Host: cerbos.acceptance.gf.ocs.nu
> User-Agent: curl/8.7.1
> Accept: */*
> Origin: https://riga.acceptance.gf.ocs.nu
>
* Request completely sent off
< HTTP/2 501
< date: Wed, 16 Oct 2024 07:40:17 GMT
< content-type: application/json
< content-length: 42
< access-control-allow-origin: https://riga.acceptance.gf.ocs.nu
< vary: Origin
< strict-transport-security: max-age=15724800; includeSubDomains
<
* Connection #0 to host cerbos.acceptance.gf.ocs.nu left intact
{"code":12,"message":"Method Not Allowed"}
```

This is running as a k8s service behind a nginx ingress, but I've tested the same configuration via a local docker image and get the same response.

I notice that in addition to the CORS headers (Vary: Origin and access-control-allow-origin), I get a HTTP error 501 back (I assume because the underlying library refuses the OPTIONS method).

Fetching from the root, I get a meaningful response:

```
> curl -v -X OPTIONS https://cerbos.acceptance.gf.ocs.nu -H "Origin: https://riga.acceptance.gf.ocs.nu"
<stripped>
< HTTP/2 200
< date: Wed, 16 Oct 2024 07:51:00 GMT
< content-type: text/html; charset=utf-8
< content-length: 783
< access-control-allow-origin: https://riga.acceptance.gf.ocs.nu
< vary: Origin
< strict-transport-security: max-age=15724800; includeSubDomains
```

Safari does use the API URL for the OPTIONS call and seems to dislike receiving an error (from the ingress log):

```
172.226.96.9 - - [16/Oct/2024:07:39:24 +0000] "OPTIONS /api/check/resources HTTP/2.0" 204 0 "https://riga.acceptance.gf.ocs.nu/" "cerbos-sdk-javascript-http/0.19.2" 291 0.000 [default-cerbos-3592] [] 10.244.177.8:3592 0 0.000 204 5f687e3da6a9881f28baef076bdf2d91
```

### Expected Behavior

I would expect to get a meaningful HTTP error code back, say 200, so to CORS request succeeds.

### Steps To Reproduce

The commands from the current behaviour are publicly executable (at the time of writing).

The URL https://riga.acceptance.gf.ocs.nu/riga/home fails (in Dutch) due to the CORS issue on Safari from MacOS Sequoia 15.1 Beta 24B5070a.  When successful, e.g., disabling CORS in developer settings, I get an (empty) table.

My setup:

Cerbos running as k8s service from Helm chart, CORS setup:
```
    server:
      cors:
        allowedOrigins:
        - "http://localhost:4200"
        - "http://localhost:8880"
        - "https://riga.acceptance.gf.ocs.nu"
```

Cerbos is exposed via nginx ingress using Let's Encrypt provisioned by certbot, exposing service:3592 as https on port 443.

Using the Javascript client (simplified from actual code)

```
const c = new HTTP("https://cerbos.acceptance.gf.ocs.nu");
const matrix = c.checkResources({
  principal: { id: i?.sub || 'ANONYMOUS', roles },
  resources,
})
```

(where id, roles, and resources are meaningful)

### Environment

- OS: Safari from MacOS Sequoia 15.1 Beta 24B5070a
- Cerbos version: 0.39.0 via helm chart 0.39.0 running on DigitalOcean managed k8s

**Comment by charithe** [comment]
Hey, your cURL command is missing the `Access-Control-Allow-Method` header required for pre-flight requests. If you add it, you'll see the correct response from Cerbos.

```
curl -v -X OPTIONS https://cerbos.acceptance.gf.ocs.nu/api/check/resources -H "Origin: https://riga.acceptance.gf.ocs.nu" -H "Access-Control-Request-Method: POST"

...
< HTTP/2 501
< date: Wed, 16 Oct 2024 09:38:51 GMT
< content-type: application/json
< content-length: 42
< access-control-allow-origin: https://riga.acceptance.gf.ocs.nu
< vary: Origin
< strict-transport-security: max-age=15724800; includeSubDomains
...
```

Based on the screenshot, Safari _is_ getting the same 204 response from Cerbos. It seems to be complaining that https://riga.acceptance.gf.ocs.nu is not in the allowed origins list. I don't know why that is though. The `access-control-allow-origin` response seems to be correctly populated by Cerbos.

**Comment by klafbang** [comment]
It was a configuration issue on my side.  Safari wants to send a user-agent header, and this seems to not be allowed with the default configuration.  Using this configuration solved the issue:

```
    server:
      cors:
        allowedOrigins:
        - "http://localhost:4200"
        - "http://localhost:8880"
        - "https://riga.acceptance.gf.ocs.nu"
        allowedHeaders:
        - User-Agent
```

It might make sense to include this header in the default configuration or mention it in the documentation in case others run into the issue?

Thanks for pointing me in the right direction, and apologies for the inconvenience.
