### ISSUE TITLE
Policies should have unique names for manipulation with admin API

### ISSUE THREAD

**Issue by aliok** [cerbos/cerbos#235]
I checked the admin API: https://docs.cerbos.dev/cerbos/api/admin_api.html. 

I wanted to see how a policy is updated.

Not sure how to update a single policy. I don't see any user defined unique fields on the policies.

Maybe I am missing a point. ... I have spent limited time on the project overall.

**Comment by aliok** [comment]
Also relevant to https://github.com/cerbos/cerbos/issues/23 IMO.

Assume the are contradicting rules in 2 policy instances. It would make sense to say "policy with name XYZ is contradicting policy with name ABC".

One level further: rules within policies can have optional names for better UX for compilation and policy validation.

**Comment by charithe** [comment]
Policies are uniquely identified using their kind, name and version (e.g. `resource:leave_request:v1`). Cerbos detects when there are two or more files with the same identifier.

Good suggestion about rule names 👍🏽
