### ISSUE TITLE
CLI needs data manipulation abilities for automation purposes

### ISSUE THREAD

**Issue by aliok** [cerbos/cerbos#236]
CLIs is cool, I really admired the NCurses like console UI :)

CLI though lacks options to manipulate policies. I think the common manipulation pattern would be still over other channels, but the manipulation with CLI would make the project easier to automate (for infra-as-code, for demos, etc.)

**Comment by isdevx** [comment]
Thanks @aliok it's great to hear that! I am personally fan of text based UIs 🙌 

Can you elaborate more about manipulating the policies with the tool? Do you mean something like an editor or some sort of command line commands to update the policies?

**Comment by oguzhand95** [comment]
Lately, we have added new `cerbosctl` commands and also changed the way some work. I think these changes cover this issue as well.

Please feel free to re-open, if you think otherwise.
