### ISSUE TITLE
Validation error messages are missing the `path` field

### ISSUE THREAD

**Issue by jbeisen** [cerbos/cerbos#2362]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

According to the OpenAPI spec, the `ValidationError` object contains a `path` field:
```json
"v1ValidationError": {
  "type": "object",
  "properties": {
    "path": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "source": {
      "$ref": "#/components/schemas/ValidationErrorSource"
    }
  }
},
```

However the actual responses from API seem to be missing the field, e.g.
```json
"validationErrors": [
  {
    "message": "missing properties: 'first_name', 'last_name'",
    "source": "SOURCE_PRINCIPAL"
  }
]
```

which I believe is causing this error in the Cerbos Python client:

  ```python
  File "/Users/jonaheisen/Library/Caches/pypoetry/virtualenvs/api--xioE9Bj-py3.10/lib/python3.10/site-packages/cerbos/sdk/_sync/_http.py", line 210, in check_resources
  File "/Users/jonaheisen/Library/Caches/pypoetry/virtualenvs/api--xioE9Bj-py3.10/lib/python3.10/site-packages/dataclasses_json/api.py", line 70, in from_dict
...
185, in _decode_dataclass
    field_value = kvs[field.name]
KeyError: 'path'
```

I'm not exactly sure if this is a problem with the Cerbos API or with the Python client, apologies if this issue belongs on the client repo.

### Expected Behavior

Expect a schema validation error not to raise an exception.

### Steps To Reproduce

1. Define a resource policy with a principal schema like this:
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "first_name": { "type": "string" },
    "last_name": { "type": "string" }
  },
  "required": ["first_name", "last_name"]
}
```

2. Run the server with schema validation on.

3. Check a resource with an invalid principal:
```python
from cerbos.sdk._sync._http import CerbosClient
from cerbos.sdk.model import Principal, ResourceAction, Resource, ResourceList

principal = Principal("123", roles={"user"})
resource_action = ResourceAction(resource=Resource(id="456", kind="api_key"), actions={"create"})

with CerbosClient(host="http://localhost:3592") as c:
    response = c.check_resources(principal=principal, resources=ResourceList(resources=[resource_action]))
```

### Environment

- OS: MacOS 14.5
- Cerbos version: 0.39.0
- Docker version: 27.2.0
- Cerbos Python client: 0.10.5

**Comment by charithe** [comment]
Thanks for reporting. Weirdly, the validation library we use doesn't populate the path for missing top-level fields. I have raised a PR to fix that.

The Python SDK shouldn't panic on missing fields either. We'll look into that as well.

**Comment by charithe** [comment]
Python SDK v0.11.0 has been released with a fix for this issue.

**Comment by jbeisen** [comment]
Thanks for the quick fix! Confirmed it's fixed - 
```python
with CerbosClient(host="http://localhost:3592") as c:
    response = c.check_resources(principal=principal, resources=ResourceList(resources=[resource_action]))
    print(response.results[0].validation_errors)
```
```
[ValidationError(message="missing properties: 'first_name', 'last_name'", source=<Source.PRINCIPAL: 'SOURCE_PRINCIPAL'>, path=None)]
```
