### ISSUE TITLE
Upgrade to goccy/go-yaml@v1.15.5

### ISSUE THREAD

**Issue by oguzhand95** [cerbos/cerbos#2401]
New version of goccy/go-yaml rewrote some parts of the parser. This results in some go panics during policy file parsing.

The PR is cerbos/cerbos#2397.

The following snippet returns nil, which results in panic:
https://github.com/goccy/go-yaml/blame/2ab584e0fa5a8ae227ce23228599f888930531ef/parser/context.go#L43-L48

It is indirectly called from https://github.com/cerbos/cerbos/blob/0a49f4206b2112270793089a76333f58ab478db3/internal/parser/parser.go#L198

**Comment by charithe** [comment]
https://github.com/goccy/go-yaml/pull/565 

#2403
