### ISSUE TITLE
Add Gofmt tool to the Makefile pre-commit target

### ISSUE THREAD

**Issue by dbuduev** [cerbos/cerbos#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

`gofmt -w -s -- -tags=tests .` runs in a pre-commit hook to format and to simplify (`-s` flag) Go code.

**Comment by charithe** [comment]
The linter is configured to automatically fix problems such as formatting (`make lint`). It runs [`gofumpt`](https://github.com/mvdan/gofumpt). Is there something missing from it?

**Comment by dbuduev** [comment]
What's missing:
1. Code simplification. `gofmt -s -d .` gives some suggestions for `internal/compile/manager_test.go`.
2. Since Go1.17 "gofmt (and go fmt) now synchronizes //go:build lines with // +build lines" as per https://golang.org/doc/go1.17#gofmt. The command gives suggestion for `tools/tools.go`

I will have a look at` gofumpt` instead.

**Comment by charithe** [comment]
Good point. Probably `gofumpt` hasn't been updated to latest changes. We could certainly configure the linter to run `gofmt` too. I don't think it will add too much overhead.
