### ISSUE TITLE
Provide error submission links in case of an error from cerbosctl

### ISSUE THREAD

**Issue by isdevx** [cerbos/cerbos#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We can provide new issue link in case of an error that has a bug potential. Eg. panic, internal errors. To demonstrate the proposal:

Let's say someone used `cerbosctl list` command, and then a panic happened in the code. We can provide some output like below:
```
$ cerbosctl list
It looks like an unexpected error happened. Would you mind reporting it to the link below?
https://github.com/cerbos/cerbos/issues/new/choose

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.17/libexec/src/runtime/debug/stack.go:24 +0x88
main.main.func1(0x14000291900)
        /Users/serdar/git/cerbos/cmd/cerbosctl/main.go:87 +0xb0
        ...

exit status 1
```

### What would the ideal solution look like to you?

We can add a `recover()` check for panics and also search for internal server error message from the error strings in the `cmd.Execute()` call:

```Go
if err := cmd.Execute(); err != nil {
	if strings.Contains(err.Error(), "code = Internal") {
		...
	}
	...
}
```

**Comment by charithe** [comment]
Capturing panics in the CLI and providing a reporting link is a good idea. 👍🏽 

Not sure about raising issues when the server returns an internal error. They are not necessarily bugs. There are lots of reasons for internal errors that are beyond our control (e.g. a database going down).

**Comment by isdevx** [comment]
Fair enough 👍 Maybe in the future we can provide a link to documentation (e.g. FAQ or troubleshooting pages) for internal errors.
