### ISSUE TITLE
Adding filtering capabilities to the list policies method of the admin API. 

### ISSUE THREAD

**Issue by isdevx** [cerbos/cerbos#297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We can enhance the list policies method by adding filtering. So, the implementation details are quite settled as we discussed before. The filtering can be done after all policies have been fetched from the store. With this, we won't need to maintain filtering logic across different store implementations. For the first iteration, the performance cost can be negligible.

So, how the filtering fields should look like? From the command line tool (`cerbosctl`) the filtering for `cerbosctl` can adopt a similar fashion with the [`kubectl`](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#viewing-finding-resources). Taken this into consideration, as we discussed [here](https://github.com/cerbos/cerbos/pull/269#discussion_r706176817) we can leverage filtering with field selectors against policies.

1. We can add basic filtering (e.g. policy kinds).
	- the kind filter should accept multiple kinds
	- disabled field (this needs confirmation) 
2. We can add advanced filtering with the field selectors.
	- filter field with an exact match (the flag can be `--field-eq` for this type of filtering)
	- filter field with wildcard match (the flag can be `--field-match` for this type)
	- search arguments should be in the form of `<field>=<value>`. For instance, if someone is looking "foo" in the resource policy description they should provide `--field-match resourcePolicy.description=foo`. Or, if they want to search "foo" among all policy kinds `--field-match description=foo`.

The API method should take either a list of basic filters or a list of advanced filters as the parameter. One thing we should consider is that whether the filter kinds above are forced to be used separately.

### What would the ideal solution look like to you?

For demonstration purposes, I am going to exemplify this with the `cerbosctl` output. The ticket includes work on both API method and the cli tool.

Current Impl. when we list the policies
```
$ cerbosctl list
NAME              KIND           DEPENDENCIES      VERSION   
donald_duck       PRINCIPAL      -                 20210210  
leave_request     RESOURCE       my_derived_roles  20210210  
leave_request     RESOURCE                         staging   
my_derived_roles  DERIVED_ROLES  -                 -     
```

We should be able to filter by kind like this:
```
$ cerbosctl list --kind principal
NAME              KIND           DEPENDENCIES      VERSION   
donald_duck       PRINCIPAL      -                 20210210  
```

Or, by field match like this:
```
$ cerbosctl list --field-eq resourcePolicy.resource=leave_request
NAME              KIND           DEPENDENCIES      VERSION   
leave_request     RESOURCE       my_derived_roles  20210210  
leave_request     RESOURCE                         staging   
```

### Anything else?

I'd like to link #136 here as this is a subset of that ticket.

**Comment by isdevx** [comment]
So, I have a working example which has a filter signature like this (for the Go client):
```Go
// FilterOpt is used to specify search terms for ListPolicies method.
type FilterOpt func(*policyFilter)

// FieldEquals adds a exact match filter for the field.
func FieldEquals(path, value string) FilterOpt {...}

// FieldEquals adds a wildcard match filter for the field.
func FieldMatches(path, value string) FilterOpt {...}
```
The ctl tool will accept flags like this (please ignore the help text field, they are just placeholders):
```bash
 cerbosctl list --help                         
List active policies

Usage:
  cerbosctl list [flags]

Flags:
      --field-eq stringArray      Filter a field with exact match
      --field-match stringArray   Filter a field with wildcard match
      --format string             Output format for the policies; json, yaml formats are supported (leave empty for pretty output)
  -h, --help                      help for list
```

And the usage looks like this:
```bash
$ cerbosctl list --field-eq resourcePolicy.resource=leave_request --field-match principalPolicy.principal=duck
NAME           KIND       DEPENDENCIES      VERSION   
donald_duck    PRINCIPAL  -                 20210210  
leave_request  RESOURCE   my_derived_roles  20210210  
leave_request  RESOURCE                     staging
```
Wildcard usage for fields, matches only for resource policy as the `resource` field only exists in resource policy:
```bash
$ cerbosctl list --field-eq="*.resource=leave_request"
NAME           KIND      DEPENDENCIES      VERSION   
leave_request  RESOURCE  my_derived_roles  20210210  
leave_request  RESOURCE                    staging   
```
Wildcard usage for fields path, this time the field exists for both resource and principal policies:
```bash
$ cerbosctl list --field-eq="*.version=20210210"      
NAME           KIND       DEPENDENCIES      VERSION   
donald_duck    PRINCIPAL  -                 20210210  
leave_request  RESOURCE   my_derived_roles  20210210  
```

I'd like to get some feedback on this. cc @charithe

**Comment by charithe** [comment]
This sounds really good. 👍🏽 

Are the wildcards glob expressions? What are the rules of evaluation? For example, are both `--field-eq="*=xx"` and  `--field-eq="**=xx"` valid? What do they match respectively? Can you match array elements using them?

Personally, I would prefer to use JSONPath expressions for field selectors because they are easier to reason about than globs and there are lots of good library implementations as well. But if there's a good case for globs, I am open for that too.

**Comment by isdevx** [comment]
Thanks for feedback 🙏 I actually leveraged a popular json library [gjson](https://github.com/tidwall/gjson) here for the example. As I was more concerned with the how API itself look like 😅  For `gjson` the wildcards are not fully compatible with common glob expressions, e.g. [abc] type matching is not available in the library but still a very capable library compared to it's usage simplicity. I think jsonpath expressions are very powerful and also `kubectl` is adopted a similar approach. We can pick either `gjson` approach or `jsonpath` approach, I think I'm fine with both. As always I'm more on simplicity side :)

**Comment by isdevx** [comment]
@charithe BTW, forgot to mention `gjson` supports array match in its own way. However, to have something more concrete you can test https://github.com/isdevx/cerbos/tree/filter-list branch. `--json-path` allows to use JSONPath expressions, otherwise it uses `gjson` way.

**Comment by charithe** [comment]
I am familiar with gjson and it's a very good choice if this command was not meant to be used by the general public. My concern is that it is a non-standard syntax that the users will need to learn whereas JSONPath is much more standardised and better known. 

If there's support for standard JSONPath as well, then I am fine with using gjson syntax as an alternative. Let's make sure it's well documented and covered by tests. I want to make sure that we don't get caught unaware if gjson developers decide to change or tweak the syntax in the future.
