### ISSUE TITLE
Generate full configuration overview from code

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#374]
The full configuration overview at https://docs.cerbos.dev/cerbos/prerelease/configuration/index.html#_full_configuration can be generated from the code automatically. It would help to keep the section of the documentation up-to-date without manual intervention.

The configuration keys in `conf.go` files are usually well documented, so that's a good starting point. We might need to use our own struct tags to make this more configurable (indicate optional fields, note mutual exclusions, show acceptable values etc.).

**Comment by oguzhand95** [comment]
I took a look at the packages you have shared and thought about how could we solve this.

Designing a go:generate tool to generate documentation from configuration structs may be a good solution.

Example;

```
```
