### ISSUE TITLE
Refactor Admin API

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#487]
`ListPolicies` returns all the policies and their contents in full -- which is not efficient and can cause resource usage peaks that are hard to predict in advance. We should instead follow the recent pattern we introduced in `ListSchemas` where the response returns only the IDs of the resources. Fetching the full definition should require a second API call to `GetPolicy`.

**Comment by oguzhand95** [comment]
While doing this change, I think the naming of the list policies should also change to follow the recent pattern in`ListSchemas`.

Currently, we use the following endpoints to list schemas and policies;
`GET /admin/schemas`
`GET /admin/policies/list`
They are inconsistent. `GET /admin/policies/list` should be `GET /admin/policies`

**Comment by charithe** [comment]
Agreed. Probably should do the same for `/admin/auditlog/list` and rename it to `/admin/auditlogs` instead. Only the URL path needs to change with that one. It should stay a streaming API.

**Comment by oguzhand95** [comment]
As retrieving the policies with ids (module id) is not feasible for the user, what should be our choice of identifier for this purpose? (`GET /admin/policy?id=<ID>`). I have thought of using FQN and came up with a working PR but I am not sure if this is the best way. WDYT?

**Comment by charithe** [comment]
FQN sounds good to me. In fact I think that's the only human readable identifier we have.

**Comment by oguzhand95** [comment]
(For future reference)

After a discussion made offline, we decided to differentiate the returned list of policies by store.
For mutable stores (databases), `<kind>.<name>.<version>` format will be used for ListPolicies and GetPolicy endpoints.
For the rest of the stores, physical file names will be used.
