### ISSUE TITLE
Inconsistent formatting of `require` blocks in `go.mod`

### ISSUE THREAD

**Issue by Juneezee** [cerbos/cerbos#528]
Currently the `go.mod` has 3 `require` blocks, while it should only have two: one for direct dependencies, and another one for indirect dependencies.

This is not a bug, but rather a small consistency issue. I can submit a PR to address this.

**Comment by charithe** [comment]
Thank you for reporting the problem. You are more than welcome to submit a PR if you would like it fix it.
