### ISSUE TITLE
Avoiding casts in numeric expressions

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#538]
CEL's strong type system does not allow operations between ints and floats without explicit casting. Furthermore, the type inference of numeric fields can be led astray by the JSON-to-protobuf conversion because all numbers are doubles in JSON and hence represented as [`number_value`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#value) by the `Value` container. This can lead to simple expressions like `request.resource.attr.someInt < 1000` actually requiring a cast: `int(request.resource.attr.someInt) < 1000`. 

Investigate whether:
- We can provide custom overrides for common arithmetic operations that work with mixed parameter types (ints and floats)
- We can utilise the schemas to "correct" the attribute values after conversion from JSON to protobuf (e.g. convert to [`Int64Value`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#int64value) or [`DoubleValue`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#doublevalue) based on schema type). This might actually require introducing a more strongly typed container to hold the attribute values passed to the engine because the `Value` container only supports only one numeric data type.
- Alternatively, during compilation, rewrite expressions to replace integer constants with double constants. (i.e. the above example would become `request.resource.attr.someInt < 1000.0`)

**Comment by dbuduev** [comment]
We can also inject a type coverstion based on a schema type. My personal preference is the second option from your list though.

**Comment by charithe** [comment]
Can you elaborate on that a bit more?

**Comment by dbuduev** [comment]
It is no longer my fav approach, but I meant this:
```go
env := conditions.StdEnv.Extend(
  cel.Declarations(
    decls.NewVar("R.attr.someInt", decls.Int),
    decls.NewVar("P.attr.anotherInt", decls.Int)))
```
where the list of those integer fields is taken from the schema.

**Comment by charithe** [comment]
Ah! Interesting idea. Definitely worth adding to the list of potential solutions.

**Comment by charithe** [comment]
I think that the new CEL release might fix this: https://github.com/google/cel-go/releases/tag/v0.10.0
I'll test it after the upgrade in #736
