### ISSUE TITLE
push_down support for persistent stores

### ISSUE THREAD

**Issue by rbtcollins** [cerbos/cerbos#539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We return 10's of thousands of objects per API call into our API. Currently authentication restrictions are pushed down into backend queries in PostgreSQL / ElasticSearch etc. This doesn't seem possible from what I can tell with Cerbos. Push down is beneficial because it prevents work and latency (e.g. to determine the full result when paginating).

### What would the ideal solution look like to you?

An API on Cerbos that permits submitting the principal and resource information and getting back an abstract filter that service code can compile into a query filter.

**Comment by charithe** [comment]
Good news! We have been working on this problem for a while. The work has already landed in `main` (#505) and we are working on polishing things up a bit before releasing -- which should be soon.
