### ISSUE TITLE
is cerbos compatible with nestjs

### ISSUE THREAD

**Issue by thorizer** [cerbos/cerbos#542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

support nestjs

### What would the ideal solution look like to you?

project example using nestjs

**Comment by alexolivier** [comment]
Yes it’s possible to use Cerbos with Next.js

We have built a demo using it along with Clerk.dev for authentication https://github.com/cerbos/nextjs-clerk-cerbos

**Comment by thorizer** [comment]
> Yes it’s possible to use Cerbos with Next.js
> 
> We have built a demo using it along with Clerk.dev for authentication https://github.com/cerbos/nextjs-clerk-cerbos
> 
> 

not nextjs but nestjs

**Comment by alexolivier** [comment]
Ah apologies- we don’t currently have a nest demo but it is on our list. 

Any of the Node examples demonstrate how it can be used in that environment along with the SDK but your request has bumped Nest up our priority list. 

https://www.npmjs.com/package/cerbos

**Comment by thorizer** [comment]
@alexolivier thank you, many users on the official Nestjs discord having issues with integrating Casl with Nestjs. we're looking for alternatives. 
I read the docs about integrating CerBos with Prisma. 
I'm using Nestjs alongside Prisma. But I'm not sure how the 3 would work together.

**Comment by lawweiliang** [comment]
@thorizer , I read an blog article regarding  NestJs + Cerbos. You may take a look.  😄 
https://cerbos.dev/blog/supercharged-authorization-for-nestjs
