### ISSUE TITLE
Use camelCase for custom functions

### ISSUE THREAD

**Issue by haines** [cerbos/cerbos#669]
The CEL function naming convention seems to be camelCase (e.g. `endsWith`, `getDayOfMonth`).

We have `inIPAddrRange` and `timeSince`, but also `has_intersection` and `is_subset`.

I think we should deprecate the snake_case versions and introduce `hasIntersection` and `isSubset`.

**Comment by charithe** [comment]
Good point! We can probably alias snake case to camel case to avoid breaking existing policies but drop the snake case versions from the documentation so that new users won't use them,
