### ISSUE TITLE
Unified check API

### ISSUE THREAD

**Issue by haines** [cerbos/cerbos#697]
At the moment we have two check APIs - `check`, and `check_resource_batch`.

For the most part, `check` (which takes a homogeneous list of resources)  is just a special case of `check_resource_batch` (which takes a heterogeneous list of resources).

However, `check` accepts `includeMeta` but `check_resource_batch` does not. Also, the response formats are quite different, making it nontrivial to replace one call with the other.

There is a cognitive load for anyone consuming the API to decide which call they need. A single unified API would be simpler to understand.

We should introduce a new unified API based on `check_resource_batch`, which should also
- support `includeMeta`
- return `resource: { kind, id }` rather than `resourceId` (to account for cases where different kinds of resource have the same id, originally proposed in https://github.com/cerbos/cerbos/issues/695)

The existing `check` and `check_resource_batch` APIs should be gradually deprecated

- reduce their prominence in the documentation (a separate "deprecated" section/page?) and add a notice to point users to the new API
- add a deprecation warning to the PDP logs

**Comment by charithe** [comment]
Questions:

- What should we name the new endpoint? 
    - `/api/v1/check`  (Adding a version component to the path. Might be confusing because the request is based on `check_resource_batch` and not `check`)
    -  `/api/decide`?
    -  `/api/eval`?
    - Other suggestions...
- Other than supporting `includeMeta` and adding `kind` to the response, what other changes are desired?

This is how the new request and response would look like:

**Request**

```json
{
  "requestId": "test",
  "includeMeta": true,
  "principal": {
    "id": "donald_duck",
    "policyVersion": "20210210",
    "roles": [
      "employee"
    ],
    "attr": {
      "department": "marketing",
      "geography": "GB",
      "team": "design"
    }
  },
  "resources": [
    {
      "actions": [
        "view:public",
        "approve",
        "create",
        "defer"
      ],
      "resource": {
        "kind": "leave_request",
        "policyVersion": "20210210",
        "id": "XX125",
        "attr": {
          "department": "marketing",
          "geography": "GB",
          "id": "XX125",
          "owner": "john",
          "team": "design"
        }
      }
    },
    {
      "actions": [
        "view:public",
        "approve",
        "create"
      ],
      "resource": {
        "kind": "leave_request",
        "policyVersion": "20210210",
        "id": "XX150",
        "attr": {
          "department": "marketing",
          "geography": "GB",
          "id": "XX125",
          "owner": "mary",
          "team": "design"
        }
      }
    }
  ],
  "auxData": {
    "jwt": {
      "token": "<token>"
    }
  }
}
```

**Response**

```json
{
  "requestId": "test",
  "results": [
    {
      "resourceId": "XX125",
      "kind": "leave_request",
      "actions": {
        "view:public": "EFFECT_ALLOW",
        "approve": "EFFECT_DENY",
        "create": "EFFECT_DENY",
        "defer": "EFFECT_DENY"
      },
      "meta": {
        "effectiveDerivedRoles": [
          "employee_that_owns_the_record",
          "any_employee"
        ],
        "actions": {
          "view:public": {
            "matchedPolicy": "resource.leave_request.v20210210"
          },
          "approve": {
            "matchedPolicy": "resource.leave_request.v20210210"
          },
          "create": {
            "matchedPolicy": "resource.leave_request.v20210210"
          },
          "defer": {
            "matchedPolicy": "resource.leave_request.v20210210"
          }
        }
      }
    },
    {
      "resourceId": "XX150",
      "kind": "leave_request",
      "actions": {
        "view:public": "EFFECT_ALLOW",
        "approve": "EFFECT_DENY",
        "create": "EFFECT_DENY"
      },
      "meta": {
        "effectiveDerivedRoles": [
          "employee_that_owns_the_record",
          "any_employee"
        ],
        "actions": {
          "view:public": {
            "matchedPolicy": "resource.leave_request.v20210210"
          },
          "approve": {
            "matchedPolicy": "resource.leave_request.v20210210"
          },
          "create": {
            "matchedPolicy": "resource.leave_request.v20210210"
          },
          "defer": {
            "matchedPolicy": "resource.leave_request.v20210210"
          }
        }
      }
    }
  ]
}
```

**Comment by haines** [comment]
Maybe `/api/check/resources`? We have `/api/x/plan/resources` so it makes sense to match `check` and `plan`.

I think the response should have `resource: { id, kind }` rather than `resourceId, kind`, for symmetry with the request.

**Comment by charithe** [comment]
Good idea! I like `/api/checkl/resources`.

The new response would look like the following with the suggested change:

```json
{
  "requestId": "test",
  "results": [
    {
      "resource": {
        "id": "XX125",
        "kind": "leave_request"
      },
      "actions": {
        "view:public": "EFFECT_ALLOW",
        "approve": "EFFECT_DENY",
        "create": "EFFECT_DENY",
        "defer": "EFFECT_DENY"
      },
      "meta": {
        "effectiveDerivedRoles": [
          "employee_that_owns_the_record",
          "any_employee"
        ],
        "actions": {
          "view:public": {
            "matchedPolicy": "resource.leave_request.v20210210"
          },
          "approve": {
            "matchedPolicy": "resource.leave_request.v20210210"
          },
          "create": {
            "matchedPolicy": "resource.leave_request.v20210210"
          },
          "defer": {
            "matchedPolicy": "resource.leave_request.v20210210"
          }
        }
      }
    },
    {
      "resource": {
        "id": "XX150",
        "kind": "leave_request"
      },
      "actions": {
        "view:public": "EFFECT_ALLOW",
        "approve": "EFFECT_DENY",
        "create": "EFFECT_DENY"
      },
      "meta": {
        "effectiveDerivedRoles": [
          "employee_that_owns_the_record",
          "any_employee"
        ],
        "actions": {
          "view:public": {
            "matchedPolicy": "resource.leave_request.v20210210"
          },
          "approve": {
            "matchedPolicy": "resource.leave_request.v20210210"
          },
          "create": {
            "matchedPolicy": "resource.leave_request.v20210210"
          },
          "defer": {
            "matchedPolicy": "resource.leave_request.v20210210"
          }
        }
      }
    }
  ]
}

```

**Comment by haines** [comment]
LGTM! `validationErrors` would be returned on the same level as `resource`, `actions`, and `meta`, right?

**Comment by charithe** [comment]
Yes. They will all be at the same level with `meta` and `validationErrors` being optional fields that are only present if `includeMeta` is true and/or if there are any validation errors.

**Comment by charithe** [comment]
I think we need to include `scope` and `version` in the `resource` field of the response as well. If the ID is not unique, then `kind`, `scope` and `version` are the other dimensions to consider when identifying a resource.

**Comment by charithe** [comment]
Follow-up tasks

- [ ] Update the SDKs to add the new endpoint
    - [x] Go (#819)
    - [ ] Java 
    - [ ] NodeJS
- [ ] Update demos to use the new API
