### ISSUE TITLE
More intervals on duration function

### ISSUE THREAD

**Issue by alexolivier** [cerbos/cerbos#705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

In CEL, the `duration()` function can only take values in:

```
Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
```

### What would the ideal solution look like to you?

For policy authoring, being able to do days/weeks/months etc would make it easier to translate requirements such as `within the last 2 weeks` or `last 7 days`

**Comment by haines** [comment]
This limitation is likely for the same reason as [Go not supporting other units](https://pkg.go.dev/time#:~:text=There%20is%20no%20definition%20for%20units%20of%20Day%20or%20larger%20to%20avoid%20confusion%20across%20daylight%20savings%20time%20zone%20transitions.)

>There is no definition for units of Day or larger to avoid confusion across daylight savings time zone transitions.
