### ISSUE TITLE
Certificate handling

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#71]
- Reloading certificates when they change
- Client certificate verification
- SPIFFE integration

Ghostunnel, Envoy, and possibly other proxies have support for all of these. The challenges are:
- We could be potentially limited/hindered by how these third-party software choose to implement them. 
- We'll have to provide documentation/support for the most popular proxies. That would require keeping up-to-date with their updates and security issues.
- Some people won't be open to running extra third-party software.

**Comment by charithe** [comment]
#1841 for reloading certificates

**Comment by tcolgate** [comment]
Closed via #1841
