### ISSUE TITLE
Expand variable aliases in PlanResources AST

### ISSUE THREAD

**Issue by haines** [cerbos/cerbos#962]
Currently the AST can contain either the full variable (e.g. `request.resource`) or the short alias (e.g. `R`), depending on what was used in the policy. It would be better to always return the full variable name so that you don't have to consider the alias as well when consuming the AST.

**Comment by dbuduev** [comment]
That makes sense, but this would be a breaking change. On the other hand, we have only a few customers using this API in production.

**Comment by charithe** [comment]
I don't think it would be a significant breaking change. As it stands, users of the API should be theoretically prepared to deal with either the long or short form unless they followed a global convention when authoring policies. By making this change we remove that uncertainty and make the API easier to reason about.
